# Generated by Django 2.1.5 on 2019-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertifiedCoach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(null=True)),
                ('source', models.CharField(blank=True, max_length=80, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, db_column='businessname', max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='postalcode', max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('business_phone', models.CharField(blank=True, db_column='businessphone', max_length=255, null=True)),
                ('mobile_phone', models.CharField(blank=True, db_column='mobilephone', max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('specialty', models.TextField()),
                ('show_in_directory', models.IntegerField(default=0)),
                ('level1_status', models.IntegerField(default=0)),
                ('level2_status', models.IntegerField(default=0)),
                ('procoach_status', models.IntegerField(default=0)),
                ('url_last_checked', models.IntegerField(null=True)),
                ('url_last_status', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'fitpro_directory',
            },
        ),
    ]
